### ISSUE TITLE
hardcoded CUDA device number

### ISSUE THREAD

**Issue by dmhowcroft** [EagleW/ReviewRobot#1]
The various `*.py` files in `Score Prediction/` have the device number hard-coded, so folks trying to train on a system using their single GPU will need to edit `cuda:1` to `cuda:0`.

Perhaps it would make sense to add a command line argument for this and keep `cuda:0` or `cuda:1` as the default?

**Comment by EagleW** [comment]
Sure, I can change them back to cuda:0 Thanks!
