### ISSUE TITLE
`acl_2017/` folder not included in repo

### ISSUE THREAD

**Issue by dmhowcroft** [EagleW/ReviewRobot#2]
Since the empty output folder can't be included in the repo, it would be nice to modify the training scripts to check if the folder exists and create it if it is not found (or to create a README or other placeholder file in the directory to be able to add the directory to the repo).

**Comment by EagleW** [comment]
Hi Please check the read me [here ](https://github.com/EagleW/ReviewRobot/blob/master/dataset/README.md)of https://drive.google.com/file/d/1NclEwGEVcHCrSWk8s3lDjvEbMlWXQoXM/view?usp=sharing

**Comment by dmhowcroft** [comment]
Ah, okay, I was just following [the top-level README](https://github.com/EagleW/ReviewRobot/blob/master/README.md) for how to run the code.
