### ISSUE TITLE
matplotlib not listed among dependencies

### ISSUE THREAD

**Issue by dmhowcroft** [EagleW/ReviewRobot#3]
in order to train the models I had to install matplotlib in my virtual environment as well.

I ended up with the following in my Pipfile (for Python 3.8 rather than 3.6):

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
torch = "==1.6.0"
numpy = "==1.19"
scipy = "==1.5.3"
networkx = "==2.5"
scikit-learn = "==0.24.0rc1"
tqdm = "==4.51"
nltk = "==3.5"
matplotlib = "*"

[requires]
python_version = "3.8"

```

Pip told me there was no `scikit-learn==0.24`, so I had to specify to use the release candidate.

**Comment by EagleW** [comment]
Thanks, I will update them!
