### ISSUE TITLE
About the preprocess.

### ISSUE THREAD

**Issue by xijuan-hdu** [EagleW/ReviewRobot#4]
Hello! When I try to preprocess the iclr dataset to get more dataset, when I changed the code and finished running, the iclr directory is empty.
And when I try to preprocess the nips dataset,the following error occured. 

File "preprocess.py", line 741, in <module>
    scores = reviews[id_]['score']
KeyError: 'pdfs1004'

**Comment by xijuan-hdu** [comment]
I think the mistake may be in your Paper-review Corpus. I find that the acl_2017's .pdf.json files have big difference with other directories. That is so sad. Because the current dataset that can be used is just the acl_2017 which is quite a small dataset. Hope for your reply. Thank you.

**Comment by EagleW** [comment]
I checked the [Paper review dataset](https://drive.google.com/file/d/1NclEwGEVcHCrSWk8s3lDjvEbMlWXQoXM/view?usp=sharing) and am pretty sure the ICLR paper is in the Raw_data

**Comment by EagleW** [comment]
Did you download it?

**Comment by EagleW** [comment]
![image](https://user-images.githubusercontent.com/14304965/203658809-fb601255-f2ef-43b9-a7ba-4ca8eef04df1.png)

**Comment by xijuan-hdu** [comment]
I download it. I mean that after the&nbsp; preprocess.py. The generate directory of icrl2017 is empty. There were no json files were generated.Which is different from the acl2017.



---Original---
From: "Qingyun ***@***.***&gt;
Date: Thu, Nov 24, 2022 07:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EagleW/ReviewRobot] About the preprocess. (Issue #4)




 
I checked the [Paper review dataset](https://drive.google.com/file/d/1NclEwGEVcHCrSWk8s3lDjvEbMlWXQoXM/view?usp=sharing) and is pretty sure the ICLR paper is in the Raw_data

**Comment by xijuan-hdu** [comment]
Thanks a lot for your reply.Like the photos show
![image](https://user-images.githubusercontent.com/78087424/203667960-12e63c19-d628-4b8a-8029-cd9fb9d6bc0a.png)
![image](https://user-images.githubusercontent.com/78087424/203667978-7d7f1b28-ef69-4fc8-a307-d9e58876f945.png)
acl_2017 can get these files,but after pre-process,iclr_2017 is a empty directory

**Comment by EagleW** [comment]
You can add the following code to the preprocess:

```python
a2id = {}
for i, a in enumerate(iclr_aspects):
    a2id[a] = i
# load review
reviews = {}
iclr_metadata_path = '../paper/iclr_2017/metadata_score_only.txt'
with open(iclr_metadata_path, 'r') as f:
    for line in tqdm(f):
        data = json.loads(line)
        id_ = data['id']
        score_mean = {}
        score_avg = {}
        tmp = [ [] for _ in range(7) ]
        for r in data['review']:
            for a in iclr_aspects:
                if a in r:
                    tmp[a2id[a]].append(r[a])
                else:
                    tmp[a2id[a]].append(0)
        count = 0
        for i in range(7):
            try:
                score_avg[acl_aspects[i]] = statistics.mean(tmp[i])
                score_mean[acl_aspects[i]] = round(score_avg[acl_aspects[i]])
            except:
                # print(id_)
                # print(acl_aspects[i])
                # print(tmp)
                count += 1
        if count == 7:
            continue
        reviews[id_] = {'score':score_mean, 'score_avg':score_avg, 'title':data['paper_content']["title"]}
idea_kbs = {}
whole_ids = []
# load idea_kb
iclr_idea_path = '../preprocess/idea_kb/iclr_2017.json'
with open(iclr_idea_path, 'r') as f:
    for line in tqdm(f):
        data = json.loads(line)
        id_ = data['id']
        whole_ids.append(id_)
        idea_kbs[id_] = data


related_kbs = {}
# load related_kb
iclr_relate_path = '../preprocess/related_kb/iclr_2017.json'
with open(iclr_relate_path, 'r') as f:
    for line in tqdm(f):
        data = json.loads(line)
        id_ = data['id']
        related_kbs[id_] = data

future_kbs = {}
# load future_kb
acl_future_path = '../preprocess/future_kb/iclr_2017.json'
with open(acl_future_path, 'r') as f:
    for line in tqdm(f):
        data = json.loads(line)
        id_ = data['id']
        future_kbs[id_] = data
assert len(idea_kbs) == len(related_kbs)

contrib_kbs = {}
# load contrib_kbs
acl_contrib_path = '../preprocess/contribute_kb/iclr_2017.json'
with open(acl_contrib_path, 'r') as f:
    for line in tqdm(f):
        data = json.loads(line)
        id_ = data['id']
        contrib_kbs[id_] = data

train_path = 'iclr_2017/%s_train.json'
valid_path = 'iclr_2017/%s_valid.json'
test_path = 'iclr_2017/%s_test.json'
for id_ in tqdm(whole_ids):
    if id_ not in reviews:
        continue
    idea_kb = idea_kbs[id_]
    related_kb = related_kbs[id_]
    future_kb = future_kbs[id_]
    contrib_kb = contrib_kbs[id_]
    scores = reviews[id_]['score']
    scores_avgs = reviews[id_]['score_avg']
    title = reviews[id_]['title']
    if id_ in iclr_dev:
        cur_path = valid_path
    elif id_ in iclr_test:
        cur_path = test_path
    else:
        cur_path = train_path
    features = {}
    for a in iclr_aspects[1:]:
        features[a] = get_features(back_kb, id2paper, related_kb, idea_kb, future_kb, key2id, a, id_, '../paper/iclr_2017/txt/', title, contrib_kb)
        score = scores[a]
        score_avg = scores_avgs[a]
        if score != 0:
            tmp = {
                'id': 'iclr_2017-' + id_, 
                'feature': features[a],
                'score': score,
                'score_avg': score_avg
            }
            with open(cur_path % a, 'a') as f:
                f.write(json.dumps(tmp)+'\n')
    score = scores['RECOMMENDATION']
    if score != 0:
        tmp = {
            'id': id_, 
            'feature': features,
            'score': score,
            'score_avg': score_avg
        }
        with open(cur_path % 'RECOMMENDATION', 'a') as f:
            f.write(json.dumps(tmp)+'\n')
```

**Comment by EagleW** [comment]
The problem with ICLR data is that it contains incomplete metadata

**Comment by xijuan-hdu** [comment]
ok thanks a lot！



---Original---
From: "Qingyun ***@***.***&gt;
Date: Sat, Dec 3, 2022 10:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EagleW/ReviewRobot] About the preprocess. (Issue #4)




 
You can add the following code to the preprocess:
 `a2id = {}
 for i, a in enumerate(iclr_aspects):
 a2id[a] = i
 
load review
 
reviews = {}
 iclr_metadata_path = '../paper/iclr_2017/metadata_score_only.txt'
 with open(iclr_metadata_path, 'r') as f:
 for line in tqdm(f):
 data = json.loads(line)
 id_ = data['id']
 score_mean = {}
 score_avg = {}
 tmp = [ [] for _ in range(7) ]
 for r in data['review']:
 for a in iclr_aspects:
 if a in r:
 tmp[a2id[a]].append(r[a])
 else:
 tmp[a2id[a]].append(0)
 count = 0
 for i in range(7):
 try:
 score_avg[acl_aspects[i]] = statistics.mean(tmp[i])
 score_mean[acl_aspects[i]] = round(score_avg[acl_aspects[i]])
 except:
 # print(id_)
 # print(acl_aspects[i])
 # print(tmp)
 count += 1
 if count == 7:
 continue
 reviews[id_] = {'score':score_mean, 'score_avg':score_avg, 'title':data['paper_content']["title"]}
 # print(id_)
 # print(score_mean)
 # input()
 
idea_kbs = {}
 whole_ids = []
 
load idea_kb
 
iclr_idea_path = '../preprocess/idea_kb/iclr_2017.json'
 with open(iclr_idea_path, 'r') as f:
 for line in tqdm(f):
 data = json.loads(line)
 id_ = data['id']
 whole_ids.append(id_)
 idea_kbs[id_] = data
 
related_kbs = {}
 
load related_kb
 
iclr_relate_path = '../preprocess/related_kb/iclr_2017.json'
 with open(iclr_relate_path, 'r') as f:
 for line in tqdm(f):
 data = json.loads(line)
 id_ = data['id']
 related_kbs[id_] = data
 
future_kbs = {}
 
load future_kb
 
acl_future_path = '../preprocess/future_kb/iclr_2017.json'
 with open(acl_future_path, 'r') as f:
 for line in tqdm(f):
 data = json.loads(line)
 id_ = data['id']
 future_kbs[id_] = data
 assert len(idea_kbs) == len(related_kbs)
 
contrib_kbs = {}
 
load contrib_kbs
 
acl_contrib_path = '../preprocess/contribute_kb/iclr_2017.json'
 with open(acl_contrib_path, 'r') as f:
 for line in tqdm(f):
 data = json.loads(line)
 id_ = data['id']
 contrib_kbs[id_] = data
 
train_path = 'merge/%s_train.json'
 valid_path = 'merge/%s_valid.json'
 test_path = 'merge/%s_test.json'
 for id_ in tqdm(whole_ids):
 if id_ not in reviews:
 continue
 idea_kb = idea_kbs[id_]
 related_kb = related_kbs[id_]
 future_kb = future_kbs[id_]
 contrib_kb = contrib_kbs[id_]
 scores = reviews[id_]['score']
 scores_avgs = reviews[id_]['score_avg']
 title = reviews[id_]['title']
 if id_ in iclr_dev:
 cur_path = valid_path
 elif id_ in iclr_test:
 cur_path = test_path
 else:
 cur_path = train_path
 features = {}
 for a in iclr_aspects[1:]:
 features[a] = get_features(back_kb, id2paper, related_kb, idea_kb, future_kb, key2id, a, id_, '../paper/iclr_2017/txt/', title, contrib_kb)
 score = scores[a]
 score_avg = scores_avgs[a]
 if score != 0:
 tmp = {
 'id': 'iclr_2017-' + id_,
 'feature': features[a],
 'score': score,
 'score_avg': score_avg
 }
 with open(cur_path % a, 'a') as f:
 f.write(json.dumps(tmp)+'\n')
 score = scores['RECOMMENDATION']
 if score != 0:
 tmp = {
 'id': id_,
 'feature': features,
 'score': score,
 'score_avg': score_avg
 }
 with open(cur_path % 'RECOMMENDATION', 'a') as f:
 f.write(json.dumps(tmp)+'\n')
 `
